server:
  port: ${PORT:8080}

security:
  oauth2:
    client:
      clientId: 8637e1875da03e60e45f
      clientSecret: 095fcbaa0c3140075f5223c2f8479e46024d38e4
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user

jwt:
  header: Authorization

---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false
ribbon:
  IsSecure: true
---

logging:
  level:
    org.springframework.security: INFO
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: 80
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.url}
    healthcheck:
      enabled: true